### ISSUE TITLE
Hi, now I have 6 mini cams connected, but I always have the same problem, together even if all online only 2 or 3 transmit at the same time.

### ISSUE THREAD

**Issue by VINCE-HA** [intx82/a9-v720#28]
***
“A9 Camera fake server” extracted from the log

2023-08-02 11:25:11,395 [WARNING] [V720-STA@7faa9fcb10] Starting video streaming
Exception in thread UDP-CON@xxx.xxx.xxx.xxx:50659:
Traceback (most recent call last):
File “/usr/lib/python3.11/threading.py”, line 1038, in _bootstrap_inner
self.run()
File “/usr/lib/python3.11/threading.py”, line 975, in run
self._target(*self._args, **self._kwargs)
File “/usr/local/a9-v720/src/v720_sta.py”, line 156, in __udp_hnd
self.__on_udp_rcv(self._udp.recv())
File “/usr/local/a9-v720/src/v720_sta.py”, line 163, in __on_udp_rcv
self._raw_hnd_lst[f’{req.cmd}’](self._udp, data)
File “/usr/local/a9-v720/src/v720_sta.py”, line 360, in __on_audio_rcv_hnd
cb(self, pkg.payload)
File “/usr/local/a9-v720/src/v720_http.py”, line 187, in _on_audio_frame
audio_queue.put_nowait(frame)
File “/usr/lib/python3.11/queue.py”, line 191, in put_nowait
return self.put(item, block=False)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File “/usr/lib/python3.11/queue.py”, line 137, in put
raise Full
queue.Full
2023-08-02 11:25:12,111 [WARNING] [V720-STA@7faa9c3d50] {
“code”: 301,
“target”: “00112233445566778899aabbccddeeff”,
“content”: {
“code”: 4,
“IrLed”: 0,
“devPower”: 92,
“speedGrade”: 1,
“moveAlert”: 0,
“sdMoveMode”: 0,
“wifiName”: “101”,
“instLed”: 1,
“sdDevStatus”: 0,
“mirrorFlip”: 0,
“version”: “202212011602”
}
}
2023-08-02 11:25:12,115 [WARNING] [V720-STA@7faa9c3d50] Starting video streaming
Exception in thread UDP-CON@xxx.xxx.xxx.xxx:2732:
Traceback (most recent call last):
File “/usr/lib/python3.11/threading.py”, line 1038, in _bootstrap_inner
self.run()
File “/usr/lib/python3.11/threading.py”, line 975, in run
self._target(*self._args, **self._kwargs)
File “/usr/local/a9-v720/src/v720_sta.py”, line 156, in __udp_hnd
self.__on_udp_rcv(self._udp.recv())
File “/usr/local/a9-v720/src/v720_sta.py”, line 163, in __on_udp_rcv
self._raw_hnd_lst[f’{req.cmd}’](self._udp, data)
File “/usr/local/a9-v720/src/v720_sta.py”, line 382, in __on_mjpg_rcv_hnd
cb(self, self._vframe)
File “/usr/local/a9-v720/src/v720_http.py”, line 195, in _on_video_frame
video_queue.put_nowait(frame)
File “/usr/lib/python3.11/queue.py”, line 191, in put_nowait
return self.put(item, block=False)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File “/usr/lib/python3.11/queue.py”, line 137, in put
raise Full
queue.Full
2023-08-02 11:25:12,367 [ ERROR] [HTTP] ffmpeg output timeout 0800c0034515@xxx.xxx.xxx.xxx:47805
2023-08-02 11:25:12,388 [ ERROR] [HTTP] ffmpeg output timeout 0800c0034515@xxx.xxx.xxx.xxx:47805

***

Thanks

**Comment by intx82** [comment]
Hi
Do you use audio stream?

Just increased a queue size, let me know the result. 

btw, overflow of queue looks like you have not very fast connection to server, i.e data from cameras incomes faster than sinks into http

**Comment by VINCE-HA** [comment]
Hi,
thank you for your intervention, sorry if I write only now,
I upgraded the "v720_http.py" file and with increased a queue size, the 6 cameras are better,
I turned off the audio at every live with camera;
I also dedicated an Access Point to them (but nothing changes in the latency);
I've done myriads of tests with many logs (I don't attach because many).

Unfortunately at the same time only 2 or 3 cams transmit live.
Here is a small excerpt from the last log:
***
A9 Camera fake server
2023-08-30 17:00:44,609  [  ERROR] [HTTP] ffmpeg output timeout 0800c0178C8D@xxx.xxx.xxx.79:5641
2023-08-30 17:00:44,653  [  ERROR] [HTTP] ffmpeg output timeout 0800c0088624@xxx.xxx.xxx.147:13583
2023-08-30 17:00:44,664  [  ERROR] [HTTP] ffmpeg output timeout 0800c0034515@xxx.xxx.xxx.171:42618
2023-08-30 17:00:44,781  [  ERROR] [HTTP] ffmpeg output timeout 0800c0020231@xxx.xxx.xxx.170:1278
2023-08-30 17:00:44,782  [  ERROR] [HTTP] ffmpeg output timeout 0800c0020231@xxx.xxx.xxx.170:1278
frame= 1086 fps=5.2 q=43.0 size=    7053kB time=00:01:48.50 bitrate= 532.5kbits/s speed=0.519x    
frame=  834 fps=0.5 q=42.0 size=    5400kB time=00:01:23.30 bitrate= 531.1kbits/s speed=0.0458x    
2023-08-30 17:00:44,875  [  ERROR] [HTTP] ffmpeg output timeout 0800c0178C8D@xxx.xxx.xxx.79:5641
2023-08-30 17:00:44,950  [  ERROR] [HTTP] ffmpeg output timeout 0800c0088624@xxx.xxx.xxx.147:13583
2023-08-30 17:00:45,030  [  ERROR] [HTTP] ffmpeg output timeout 0800c0020231@xxx.xxx.xxx.170:1278
frame=  673 fps=2.1 q=33.0 size=    4376kB time=00:01:07.21 bitrate= 533.4kbits/s speed=0.208x    
2023-08-30 17:00:45,075  [  ERROR] [HTTP] ffmpeg output timeout 0800c0020231@xxx.xxx.xxx.170:1278
2023-08-30 17:00:45,128  [  ERROR] [HTTP] ffmpeg output timeout 0800c0086582@xxx.xxx.xxx.146:62702
2023-08-30 17:00:45,244  [  ERROR] [HTTP] ffmpeg output timeout 0800c0077296@xxx.xxx.xxx.150:25993
2023-08-30 17:00:45,264  [  ERROR] [HTTP] ffmpeg output timeout 0800c0086582@xxx.xxx.xxx.146:62702
2023-08-30 17:00:45,346  [  ERROR] [HTTP] ffmpeg output timeout 0800c0020231@xxx.xxx.xxx.170:1278
frame=  834 fps=0.5 q=42.0 size=    5400kB time=00:01:23.30 bitrate= 531.1kbits/s speed=0.0458x    
2023-08-30 17:00:45,389  [  ERROR] [HTTP] ffmpeg output timeout 0800c0086582@xxx.xxx.xxx.146:62702
2023-08-30 17:00:45,445  [  ERROR] [HTTP] ffmpeg output timeout 0800c0034515@xxx.xxx.xxx.171:42618
2023-08-30 17:00:45,482  [  ERROR] [HTTP] ffmpeg output timeout 0800c0086582@xxx.xxx.xxx.146:62702
frame=  673 fps=2.1 q=33.0 size=    4376kB time=00:01:07.21 bitrate= 533.4kbits/s speed=0.207x    
2023-08-30 17:00:45,701  [  ERROR] [HTTP] ffmpeg output timeout 0800c0178C8D@xxx.xxx.xxx.79:5641
2023-08-30 17:00:45,730  [  ERROR] [HTTP] ffmpeg output timeout 0800c0034515@xxx.xxx.xxx.171:42618
frame= 1086 fps=5.2 q=43.0 size=    7053kB time=00:01:48.50 bitrate= 532.5kbits/s speed=0.517x    
frame=  834 fps=0.5 q=42.0 size=    5400kB time=00:01:23.30 bitrate= 531.1kbits/s speed=0.0458x    
frame=  673 fps=2.1 q=33.0 size=    4376kB time=00:01:07.21 bitrate= 533.4kbits/s speed=0.207x    
2023-08-30 17:00:46,152  [  ERROR] [HTTP] ffmpeg output timeout 0800c0178C8D@xxx.xxx.xxx.79:25438
2023-08-30 17:00:46,316  [  ERROR] [HTTP] ffmpeg output timeout 0800c0020231@xxx.xxx.xxx.170:1278
frame= 1086 fps=5.2 q=43.0 size=    7053kB time=00:01:48.50 bitrate= 532.5kbits/s speed=0.515x    
2023-08-30 17:00:46,351  [  ERROR] [HTTP] ffmpeg output timeout 0800c0034515@xxx.xxx.xxx.171:42618
frame=  834 fps=0.5 q=42.0 size=    5400kB time=00:01:23.30 bitrate= 531.1kbits/s speed=0.0457x    
frame=  673 fps=2.1 q=33.0 size=    4376kB time=00:01:07.21 bitrate= 533.4kbits/s speed=0.207x    
2023-08-30 17:00:46,610  [  ERROR] [HTTP] ffmpeg output timeout 0800c0178C8D@xxx.xxx.xxx.79:5641
2023-08-30 17:00:46,656  [  ERROR] [HTTP] ffmpeg output timeout 0800c0088624@xxx.xxx.xxx.147:13583
2023-08-30 17:00:46,666  [  ERROR] [HTTP] ffmpeg output timeout 0800c0034515@xxx.xxx.xxx.171:42618
2023-08-30 17:00:46,782  [  ERROR] [HTTP] ffmpeg output timeout 0800c0020231@xxx.xxx.xxx.170:1278
2023-08-30 17:00:46,783  [  ERROR] [HTTP] ffmpeg output timeout 0800c0020231@xxx.xxx.xxx.170:1278
frame= 1086 fps=5.1 q=43.0 size=    7053kB time=00:01:48.50 bitrate= 532.5kbits/s speed=0.514x    
2023-08-30 17:00:46,876  [  ERROR] [HTTP] ffmpeg output timeout 0800c0178C8D@xxx.xxx.xxx.79:5641
frame=  834 fps=0.5 q=42.0 size=    5400kB time=00:01:23.30 bitrate= 531.1kbits/s speed=0.0457x    
2023-08-30 17:00:46,951  [  ERROR] [HTTP] ffmpeg output timeout 0800c0088624@xxx.xxx.xxx.147:13583
2023-08-30 17:00:47,031  [  ERROR] [HTTP] ffmpeg output timeout 0800c0020231@xxx.xxx.xxx.170:1278
2023-08-30 17:00:47,076  [  ERROR] [HTTP] ffmpeg output timeout 0800c0020231@xxx.xxx.xxx.170:1278
frame=  673 fps=2.1 q=33.0 size=    4376kB time=00:01:07.21 bitrate= 533.4kbits/s speed=0.206x    
2023-08-30 17:00:47,130  [  ERROR] [HTTP] ffmpeg output timeout 0800c0086582@xxx.xxx.xxx.146:62702
2023-08-30 17:00:47,245  [  ERROR] [HTTP] ffmpeg output timeout 0800c0077296@xxx.xxx.xxx.150:25993
2023-08-30 17:00:47,265  [  ERROR] [HTTP] ffmpeg output timeout 0800c0086582@xxx.xxx.xxx.146:62702
frame= 1086 fps=5.1 q=43.0 size=    7053kB time=00:01:48.50 bitrate= 532.5kbits/s speed=0.513x    
2023-08-30 17:00:47,347  [  ERROR] [HTTP] ffmpeg output timeout 0800c0020231@xxx.xxx.xxx.170:1278
frame=  834 fps=0.5 q=42.0 size=    5400kB time=00:01:23.30 bitrate= 531.1kbits/s speed=0.0457x    
2023-08-30 17:00:47,391  [  ERROR] [HTTP] ffmpeg output timeout 0800c0086582@xxx.xxx.xxx.146:62702
2023-08-30 17:00:47,446  [  ERROR] [HTTP] ffmpeg output timeout 0800c0034515@xxx.xxx.xxx.171:42618
2023-08-30 17:00:47,483  [  ERROR] [HTTP] ffmpeg output timeout 0800c0086582@xxx.xxx.xxx.146:62702
frame=  673 fps=2.1 q=33.0 size=    4376kB time=00:01:07.21 bitrate= 533.4kbits/s speed=0.206x    
2023-08-30 17:00:47,702  [  ERROR] [HTTP] ffmpeg output timeout 0800c0178C8D@xxx.xxx.xxx.79:5641
2023-08-30 17:00:47,731  [  ERROR] [HTTP] ffmpeg output timeout 0800c0034515@xxx.xxx.xxx.171:42618
frame= 1086 fps=5.1 q=43.0 size=    7053kB time=00:01:48.50 bitrate= 532.5kbits/s speed=0.512x    
frame=  834 fps=0.5 q=42.0 size=    5400kB time=00:01:23.30 bitrate= 531.1kbits/s speed=0.0457x    
frame=  673 fps=2.1 q=33.0 size=    4376kB time=00:01:07.21 bitrate= 533.4kbits/s speed=0.206x    
2023-08-30 17:00:48,154  [  ERROR] [HTTP] ffmpeg output timeout 0800c0178C8D@xxx.xxx.xxx.79:25438
2023-08-30 17:00:48,317  [  ERROR] [HTTP] ffmpeg output timeout 0800c0020231@xxx.xxx.xxx.170:1278
frame= 1086 fps=5.1 q=43.0 size=    7053kB time=00:01:48.50 bitrate= 532.5kbits/s speed=0.51x    
2023-08-30 17:00:48,353  [  ERROR] [HTTP] ffmpeg output timeout 0800c0034515@xxx.xxx.xxx.171:42618
***
If you need more data, I'll be ready to send them,
thanks a lot and greetings,
VC

**Comment by VINCE-HA** [comment]
Hi,
unfortunately the problem is not solved yet
:-)

**Comment by intx82** [comment]
Could you start the server with argument `-v` and upload logs somewhere.

**Comment by intx82** [comment]
```
python3 src/a9_naxclow.py -s -v > a9.log
```

And attach 'a9.log' file here

**Comment by VINCE-HA** [comment]
Hi, I'm sorry but with the command you suggested I don't have any A9.log file.
this is an extract of the log that I can get from the Home Assistant web interface -A9 Camera fake server-, if you can kindly give me some other indication as the problem persists; 3 or 4 A9webcams always provide the live broadcast, the others do not transmit the stream even if connected to the dedicated access point.
Thanks always,
VC

***
Start Server
***

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------
 Add-on: A9 Camera fake server
 A9 Cam fake server
-----------------------------------------------------------
 Add-on version: 2.4
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.5  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.9.1
 Home Assistant Supervisor: 2023.08.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init: starting
s6-rc: info: service init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
-------- A9 V720 fake-server starting. --------
Stream: http://127.0.0.1:80/dev/None/stream
Snapshot: http://127.0.0.1:80/dev/None/snapshot
IrLed: http://127.0.0.1:80/dev/None/cmd?code=202&IrLed=1
Flip: http://127.0.0.1:80/dev/None/cmd?code=216&mirrorFlip=4
2023-09-09 16:27:36,561  [WARNING] [HTTP] POST /app/api/ApiServer/getA9ConfCheck?devicesCode=0800c0077296&random=NOPQRS&token=0e9ba3a172
-------- Found device 0800c0077296 --------
Stream: http://127.0.0.1:80/dev/0800c0077296/stream
Snapshot: http://127.0.0.1:80/dev/0800c0077296/snapshot
IrLed: http://127.0.0.1:80/dev/0800c0077296/cmd?code=202&IrLed=1
Flip: http://127.0.0.1:80/dev/0800c0077296/cmd?code=216&mirrorFlip=4
2023-09-09 16:29:43,985  [WARNING] [HTTP] POST /app/api/ApiServer/getA9ConfCheck?devicesCode=0800c0020231&random=BCDEFG&token=ee0eb37ecb
-------- Found device 0800c0020231 --------
Stream: http://127.0.0.1:80/dev/0800c0020231/stream
Snapshot: http://127.0.0.1:80/dev/0800c0020231/snapshot
IrLed: http://127.0.0.1:80/dev/0800c0020231/cmd?code=202&IrLed=1
Flip: http://127.0.0.1:80/dev/0800c0020231/cmd?code=216&mirrorFlip=4
2023-09-09 16:30:14,637  [WARNING] [HTTP] POST /app/api/ApiServer/getA9ConfCheck?devicesCode=0800c0088624&random=OPQRST&token=f2c0a73e17
-------- Found device 0800c0088624 --------
Stream: http://127.0.0.1:80/dev/0800c0088624/stream
Snapshot: http://127.0.0.1:80/dev/0800c0088624/snapshot
IrLed: http://127.0.0.1:80/dev/0800c0088624/cmd?code=202&IrLed=1
Flip: http://127.0.0.1:80/dev/0800c0088624/cmd?code=216&mirrorFlip=4
2023-09-09 16:31:05,498  [WARNING] [HTTP] POST /app/api/ApiServer/getA9ConfCheck?devicesCode=0800c0034515&random=JKLMNO&token=a7731ace27
-------- Found device 0800c0034515 --------
Stream: http://127.0.0.1:80/dev/0800c0034515/stream
Snapshot: http://127.0.0.1:80/dev/0800c0034515/snapshot
IrLed: http://127.0.0.1:80/dev/0800c0034515/cmd?code=202&IrLed=1
Flip: http://127.0.0.1:80/dev/0800c0034515/cmd?code=216&mirrorFlip=4
2023-09-09 16:31:57,105  [WARNING] [HTTP] POST /app/api/ApiServer/getA9ConfCheck?devicesCode=0800c0178C8D&random=YZABCD&token=d96412d9eb
-------- Found device 0800c0178C8D --------
Stream: http://127.0.0.1:80/dev/0800c0178C8D/stream
Snapshot: http://127.0.0.1:80/dev/0800c0178C8D/snapshot
IrLed: http://127.0.0.1:80/dev/0800c0178C8D/cmd?code=202&IrLed=1
Flip: http://127.0.0.1:80/dev/0800c0178C8D/cmd?code=216&mirrorFlip=4
2023-09-09 16:32:15,763  [WARNING] [HTTP] POST /app/api/ApiServer/getA9ConfCheck?devicesCode=0800c0086582&random=JKLMNO&token=b5a8a95328
-------- Found device 0800c0086582 --------
Stream: http://127.0.0.1:80/dev/0800c0086582/stream
Snapshot: http://127.0.0.1:80/dev/0800c0086582/snapshot
IrLed: http://127.0.0.1:80/dev/0800c0086582/cmd?code=202&IrLed=1
Flip: http://127.0.0.1:80/dev/0800c0086582/cmd?code=216&mirrorFlip=4

***
when the problems start
***

2023-09-09 16:19:35,112  [WARNING] [V720-STA@7f8476a0d0] Starting video streaming
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/a9-v720/src/v720_sta.py", line 156, in __udp_hnd
    self.__on_udp_rcv(self._udp.recv())
  File "/usr/local/a9-v720/src/v720_sta.py", line 163, in __on_udp_rcv
    self._raw_hnd_lst[f'{req.cmd}'](self._udp, data)
  File "/usr/local/a9-v720/src/v720_sta.py", line 360, in __on_audio_rcv_hnd
    cb(self, pkg.payload)
  File "/usr/local/a9-v720/src/v720_http.py", line 187, in _on_audio_frame
    audio_queue.put_nowait(frame)
  File "/usr/lib/python3.11/queue.py", line 191, in put_nowait
    return self.put(item, block=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/queue.py", line 137, in put
    raise Full
queue.Full
2023-09-09 16:19:35,505  [  ERROR] [HTTP] ffmpeg output timeout 0800c0086582@xxx.xxx.xxx.146:30335
2023-09-09 16:19:35,538  [  ERROR] [HTTP] ffmpeg output timeout 0800c0086582@xxx.xxx.xxx.146:30335
2023-09-09 16:19:35,598  [  ERROR] [HTTP] ffmpeg output timeout 0800c0086582@xxx.xxx.xxx.146:30335
2023-09-09 16:19:36,776  [  ERROR] [HTTP] ffmpeg output timeout 0800c0034515@xxx.xxx.xxx.171:27275
2023-09-09 16:19:36,785  [  ERROR] [HTTP] ffmpeg output timeout 0800c0034515@xxx.xxx.xxx.171:27275
2023-09-09 16:19:37,506  [  ERROR] [HTTP] ffmpeg output timeout 0800c0086582@xxx.xxx.xxx.146:30335
2023-09-09 16:19:37,539  [  ERROR] [HTTP] ffmpeg output timeout 0800c0086582@xxx.xxx.xxx.146:30335
2023-09-09 16:19:37,599  [  ERROR] [HTTP] ffmpeg output timeout 0800c0086582@xxx.xxx.xxx.146:30335
2023-09-09 16:19:38,777  [  ERROR] [HTTP] ffmpeg output timeout 0800c0034515@xxx.xxx.xxx.171:27275
2023-09-09 16:19:38,786  [  ERROR] [HTTP] ffmpeg output timeout 0800c0034515@xxx.xxx.xxx.171:27275
2023-09-09 16:19:39,507  [  ERROR] [HTTP] ffmpeg output timeout 0800c0086582@xxx.xxx.xxx.146:30335
2023-09-09 16:19:39,540  [  ERROR] [HTTP] ffmpeg output timeout 0800c0086582@xxx.xxx.xxx.146:30335
2023-09-09 16:19:39,600  [  ERROR] [HTTP] ffmpeg output timeout 0800c0086582@xxx.xxx.xxx.146:30335

***
when the problems continue
***

2023-09-09 16:24:25,081  [WARNING] [V720-STA@7f84757b90] Starting video streaming
Exception in thread UDP-CON@xxx.xxx.xxx.146:45095:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/a9-v720/src/v720_sta.py", line 156, in __udp_hnd
    self.__on_udp_rcv(self._udp.recv())
  File "/usr/local/a9-v720/src/v720_sta.py", line 163, in __on_udp_rcv
    self._raw_hnd_lst[f'{req.cmd}'](self._udp, data)
  File "/usr/local/a9-v720/src/v720_sta.py", line 360, in __on_audio_rcv_hnd
    cb(self, pkg.payload)
  File "/usr/local/a9-v720/src/v720_http.py", line 187, in _on_audio_frame
    audio_queue.put_nowait(frame)
  File "/usr/lib/python3.11/queue.py", line 191, in put_nowait
    return self.put(item, block=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/queue.py", line 137, in put
    raise Full
queue.Full

**Comment by intx82** [comment]
Updated, could you please try again and let me know about results

**Comment by VINCE-HA** [comment]
> Updated, could you please try again and let me know about results

I replied by email, thanks

**Comment by intx82** [comment]
Hi again, have faced on my setup with yours issue.
Could be reproduced on my side if used direct capturing via ffmpeg with several cameras

**Comment by VINCE-HA** [comment]
Hi, sorry I don't understand what you mean by "direct acquisition via ffmpeg";
See you soon, V.C

**Comment by intx82** [comment]
i mean, i have setup which have at home Raspberry Pi with this server and remote VPS where started several ffmpegs which connects to the rpi via http-mjpg stream and records to internal drive what's happens in the apartment

**Comment by VINCE-HA** [comment]
ok thanks I understand;
I'm waiting for your news, in the meantime I also continue to do tests on Raspberry Pi Home Assistant with the A9 Camera fake server add-on, but I don't know where to change the code, some camA9 cameras randomly stop transmitting, they respond to the ping but I have to restart them manually so that they return to forward the video... regards, VC
